export DashBoard from './DashBoard'
export Home from './Home'
export Login from './Login'
export User from './User'
export ShotDetail from './ShotDetail'
export Found from './Found'
export Message from './Message'
